// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGhX0kMbHHtLZ9_lN__7lywQynoC6VmRY',
    appId: '1:794287977118:android:bba4eb8769765100c3418f',
    messagingSenderId: '794287977118',
    projectId: 'rumah-jahit-alya',
    storageBucket: 'rumah-jahit-alya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTVZFFS9DjYwFRDIdof_eaa3_IfgqbL-E',
    appId: '1:794287977118:ios:127da440202dc240c3418f',
    messagingSenderId: '794287977118',
    projectId: 'rumah-jahit-alya',
    storageBucket: 'rumah-jahit-alya.firebasestorage.app',
    iosBundleId: 'com.example.rumahJahit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-3uQD5pHtcCH4BCKifMmDlnULw1z-s1k',
    appId: '1:794287977118:web:a64293abb5a40782c3418f',
    messagingSenderId: '794287977118',
    projectId: 'rumah-jahit-alya',
    authDomain: 'rumah-jahit-alya.firebaseapp.com',
    storageBucket: 'rumah-jahit-alya.firebasestorage.app',
    measurementId: 'G-X8YM3TFZ61',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-3uQD5pHtcCH4BCKifMmDlnULw1z-s1k',
    appId: '1:794287977118:web:a64293abb5a40782c3418f',
    messagingSenderId: '794287977118',
    projectId: 'rumah-jahit-alya',
    authDomain: 'rumah-jahit-alya.firebaseapp.com',
    storageBucket: 'rumah-jahit-alya.firebasestorage.app',
    measurementId: 'G-X8YM3TFZ61',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTVZFFS9DjYwFRDIdof_eaa3_IfgqbL-E',
    appId: '1:794287977118:ios:127da440202dc240c3418f',
    messagingSenderId: '794287977118',
    projectId: 'rumah-jahit-alya',
    storageBucket: 'rumah-jahit-alya.firebasestorage.app',
    iosBundleId: 'com.example.rumahJahit',
  );

}