import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:rumah_jahit/core/utils/currency_utils.dart';
import 'package:rumah_jahit/features/payroll/data/payroll_providers.dart';
import 'package:rumah_jahit/features/payroll/domain/payroll_record.dart';

class PayrollAdjustmentsCard extends ConsumerStatefulWidget {
  final String userId;
  final String userName;

  const PayrollAdjustmentsCard({
    super.key,
    required this.userId,
    required this.userName,
  });

  @override
  ConsumerState<PayrollAdjustmentsCard> createState() =>
      _PayrollAdjustmentsCardState();
}

class _PayrollAdjustmentsCardState
    extends ConsumerState<PayrollAdjustmentsCard> {
  final _bonusAmountController = TextEditingController();
  final _bonusNoteController = TextEditingController();
  final _deductionAmountController = TextEditingController();
  final _deductionNoteController = TextEditingController();

  bool _isLoading = false;

  @override
  void dispose() {
    _bonusAmountController.dispose();
    _bonusNoteController.dispose();
    _deductionAmountController.dispose();
    _deductionNoteController.dispose();
    super.dispose();
  }

  Future<void> _applyAdjustment(bool isBonus) async {
    final amountController =
        isBonus ? _bonusAmountController : _deductionAmountController;
    final noteController =
        isBonus ? _bonusNoteController : _deductionNoteController;

    final numericString =
        amountController.text.replaceAll(RegExp(r'[^0-9]'), '');
    final amount = double.tryParse(numericString) ?? 0;

    if (amount <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Jumlah tidak valid'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    if (noteController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Alasan harus diisi'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final record = PayrollRecord(
        id: '', // Will be generated by Firestore
        userId: widget.userId,
        userName: widget.userName,
        type: 'adjustment',
        note: noteController.text.trim(),
        piecesCount: 0,
        wagePerPiece: isBonus ? amount : -amount,
        totalWage: isBonus ? amount : -amount,
        status: 'UNPAID',
        createdAt: DateTime.now(),
      );

      await ref.read(payrollRepositoryProvider).generate(record);

      if (mounted) {
        amountController.clear();
        noteController.clear();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(isBonus ? 'Bonus berhasil ditambah' : 'Potongan berhasil ditambah'),
            backgroundColor: isBonus ? Colors.green : Colors.orange,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Gagal menyimpan: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 6,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: Theme.of(context).colorScheme.primaryContainer.withValues(alpha: 0.5),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Icon(
                  Icons.payments_outlined,
                  color: Theme.of(context).colorScheme.primary,
                  size: 20,
                ),
              ),
              const SizedBox(width: 12),
              Text(
                'Penyesuaian Gaji',
                style: GoogleFonts.manrope(
                  fontSize: 16,
                  fontWeight: FontWeight.w800,
                  color: Theme.of(context).colorScheme.primary,
                ),
              ),
            ],
          ),
          const SizedBox(height: 24),

          // BONUS SECTION
          Text(
            'TAMBAH BONUS (RP)',
            style: GoogleFonts.inter(
              fontSize: 10,
              fontWeight: FontWeight.w800,
              letterSpacing: 0.5,
              color: Colors.grey.shade500,
            ),
          ),
          const SizedBox(height: 8),
          _buildTextField(
            controller: _bonusAmountController,
            hint: '0',
            prefixText: 'Rp  ',
            keyboardType: TextInputType.number,
            formatters: [CurrencyInputFormatter()],
          ),
          const SizedBox(height: 12),
          _buildTextField(
            controller: _bonusNoteController,
            hint: 'Alasan (Contoh: Bonus Lebaran)',
          ),
          const SizedBox(height: 12),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              onPressed: _isLoading ? null : () => _applyAdjustment(true),
              icon: const Icon(Icons.add, size: 16),
              label: Text(
                'Tambah Bonus',
                style: GoogleFonts.inter(fontWeight: FontWeight.w700),
              ),
              style: ElevatedButton.styleFrom(
                backgroundColor: Theme.of(context).colorScheme.primary,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 14),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                elevation: 0,
              ),
            ),
          ),
          const SizedBox(height: 24),

          // DEDUCTION SECTION
          Text(
            'POTONGAN / AMBIL GAJI (RP)',
            style: GoogleFonts.inter(
              fontSize: 10,
              fontWeight: FontWeight.w800,
              letterSpacing: 0.5,
              color: Colors.grey.shade500,
            ),
          ),
          const SizedBox(height: 8),
          _buildTextField(
            controller: _deductionAmountController,
            hint: '0',
            prefixText: 'Rp  ',
            prefixColor: Colors.red.shade700,
            keyboardType: TextInputType.number,
            formatters: [CurrencyInputFormatter()],
          ),
          const SizedBox(height: 12),
          _buildTextField(
            controller: _deductionNoteController,
            hint: 'Alasan (Contoh: Ambil Gaji Awal)',
          ),
          const SizedBox(height: 12),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              onPressed: _isLoading ? null : () => _applyAdjustment(false),
              icon: const Icon(Icons.remove, size: 16),
              label: Text(
                'Kurangi Gaji',
                style: GoogleFonts.inter(fontWeight: FontWeight.w700),
              ),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.red.shade800,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 14),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                elevation: 0,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String hint,
    String? prefixText,
    Color? prefixColor,
    TextInputType? keyboardType,
    List<TextInputFormatter>? formatters,
  }) {
    return TextField(
      controller: controller,
      keyboardType: keyboardType,
      inputFormatters: formatters,
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: GoogleFonts.inter(color: Colors.grey.shade500, fontSize: 13),
        prefixText: prefixText,
        prefixStyle: GoogleFonts.inter(
          color: prefixColor ?? Theme.of(context).colorScheme.primary,
          fontWeight: FontWeight.w700,
          fontSize: 14,
        ),
        filled: true,
        fillColor: const Color(0xFFF2F4F4),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
      ),
    );
  }
}
